#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="${SERVICE_NAME:-readest-webdav}"
PROJECT_ID="${PROJECT_ID:-}"
REGION="${REGION:-us-west1}"
SUPABASE_STORAGE_BUCKET="${SUPABASE_STORAGE_BUCKET:-readest}"
STORAGE_BACKEND="${STORAGE_BACKEND:-supabase}"
WEBDAV_USERNAME="${WEBDAV_USERNAME:-readest}"
WEBDAV_ROOT_PREFIX="${WEBDAV_ROOT_PREFIX:-}"
WEBDAV_HIDE_LEGACY_ROOT_FOLDER="${WEBDAV_HIDE_LEGACY_ROOT_FOLDER:-true}"
WEBDAV_LEGACY_TOP_LEVEL_PREFIX="${WEBDAV_LEGACY_TOP_LEVEL_PREFIX:-}"
WEBDAV_VIRTUAL_ROOT_ALIASES="${WEBDAV_VIRTUAL_ROOT_ALIASES:-}"

project_args=()
if [ -n "$PROJECT_ID" ]; then
  project_args+=(--project "$PROJECT_ID")
fi

gcloud run deploy "$SERVICE_NAME" \
  "${project_args[@]}" \
  --source . \
  --region "$REGION" \
  --min-instances 0 \
  --max-instances "${MAX_INSTANCES:-3}" \
  --cpu 1 \
  --memory 512Mi \
  --timeout 300 \
  --no-invoker-iam-check \
  --set-env-vars "SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET},STORAGE_BACKEND=${STORAGE_BACKEND},WEBDAV_USERNAME=${WEBDAV_USERNAME},WEBDAV_ROOT_PREFIX=${WEBDAV_ROOT_PREFIX},WEBDAV_HIDE_LEGACY_ROOT_FOLDER=${WEBDAV_HIDE_LEGACY_ROOT_FOLDER},WEBDAV_LEGACY_TOP_LEVEL_PREFIX=${WEBDAV_LEGACY_TOP_LEVEL_PREFIX},WEBDAV_VIRTUAL_ROOT_ALIASES=${WEBDAV_VIRTUAL_ROOT_ALIASES}" \
  --set-secrets "SUPABASE_URL=supabase-url:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest,WEBDAV_PASSWORD=readest-webdav-password:latest"
